### ISSUE TITLE
Autocomplete for predicates

### ISSUE THREAD

**Issue by jamesaoverton** [knotation/knotation-editor#10]
For a first pass at autocomplete, I would like completion for the predicate position. The list of suggestions should be provided by the user as list of labels when the editor is configured. The autocomplete should filter by prefix, preserving the order of the suggestions.

It would also be good to provide methods for adding and removing suggestions for the editor.

**Comment by inaimathi** [comment]
Addressed in https://github.com/knotation/knotation-editor/pull/17
