### ISSUE TITLE
Sequence of output editors

### ISSUE THREAD

**Issue by jamesaoverton** [knotation/knotation-editor#15]
The current `linked-editors` handles multiple output editors as a map. I'd prefer to provide a sequence of editors (already initialized by `editor!`).

**Comment by jamesaoverton** [comment]
Clarification. The signature should be: one env editor, one input editor, sequence of output editors.

**Comment by inaimathi** [comment]
Fair enough. My reasoning for taking editors as keyword args was that we might want a `ttl` editor, but no `nq` editor some places. If we picked an order for this, a call to `linked-editor` might end up looking like `(linked-editor env prefix input nil nq nil)`. Having keyworded inputs would also let us specify multiple editors of a particular kind like `(linked-editor :env [a b c] :prefix [d e] :input f :ttl f :rdfa g)`, which seems like it would be more confusing with a flat sequence input. 

We should make the most common use-case easy though; I'm going to change the `linked-editors` function to have args `[env input ttl nq rdfa]`, and add a separate `linked` function to allow for more elaborate calls.

**Comment by inaimathi** [comment]
Addressed in https://github.com/knotation/knotation-editor/pull/16

**Comment by jamesaoverton** [comment]
I want to do something like this:

    (let [context (ed/editor! "#context textarea" :mode "knotation")
          content (ed/editor! "#content textarea" :mode "knotation")
          tree (ed/editor! "#tree-editor" :mode "json")
          dot (ed/editor! "#dot-editor" :mode "dot")]
      (ed/link! context content [tree dot])
      (.on tree "compiled-to"
          (fn [ed content]
            ;; update bootstrap tree view
          ))
      (.on dot "compiled-to"
          (fn [ed content]
            ;; update viz
          ))
    )

**Comment by inaimathi** [comment]
So, as of the latest commit you can write 

```
(let [context (ed/editor! "#context textarea" :mode "knotation")
      content (ed/editor! "#content textarea" :mode "knotation")
      tree (ed/editor! "#tree-editor" :mode "tree")
      dot (ed/editor! "#dot-editor" :mode "dot")]
  (ed/link! context content [tree dot])
  (.on tree "compiled-to"
      (fn [ed content]
        ;; update bootstrap tree view
      ))
  (.on dot "compiled-to"
      (fn [ed content]
        ;; update viz
      ))
)
```

(Note the `"tree"` mode in the `tree` editor; the idea is that this is the thing we pass to `knotation-cljc.api/output`). That way we can have an arbitrary number of outputs, and each output is treated appropriately according to its `mode` setting. There's a mapping between `mode` and `format` that's explicitly coded in `knotation.editor.core`, which we'll need to update with any modes we add to `knotation-cljc`.
