### ISSUE TITLE
Add Knotation syntax highlighting

### ISSUE THREAD

**Issue by jamesaoverton** [knotation/knotation-editor#2]
We need a preliminary syntax highlighter. For a first pass it should:

- match `@prefix` as a keyword
- match `: .*` lines as a subject, in bold or something
- match `^.*: ` as a predicate, coloured somehow
- match wrapped IRIs (e.g. `<foo>`), coloured somehow

We can probably start with the CodeMirror modes for Turtle or N-Triples.

Eventually we want to integrate closely with the Knotation library, to distinguish labels from strings, known labels from missing labels, report errors, and suggest predicates and labels. That can all wait, but it's worth thinking about as we figure out CodeMirror modes.

**Comment by inaimathi** [comment]
As of https://github.com/knotation/knotation-editor/commit/e9cd302f9e1e436dc7789d95957d70bc46143ec0, we've got a working highlight mode that fits the above criteria
