### ISSUE TITLE
Add CodeMirror.fromTextArea

### ISSUE THREAD

**Issue by jamesaoverton** [knotation/knotation-editor#4]

**Comment by inaimathi** [comment]
As of https://github.com/knotation/knotation-editor/commit/a8d8e0f13b3091d7840e30d81e2ca9cb4db9c0e1, the default `fromSelector` and `editor!` functions dispatch on the given element type, and call either `CodeMirror` or `CodeMirror.fromTextArea` as appropriate.

This gives us the desired functionality without introducing new API elements into the mix.
